### ISSUE TITLE
Footer element in compose element results in error

### ISSUE THREAD

**Issue by YardGnomeNinja** [aurelia/templating-resources#351]
**I'm submitting a bug report**

* **Library Version:**
1.7.0

**Please tell us about your environment:**
* **Operating System:**
Windows 10

* **Node Version:**
v8.11.3

* **NPM Version:**
6.1.0

* **JSPM OR Webpack AND Version**
webpack 4.1.1

* **Browser:**
Chrome 67.0.3396.87

* **Language:**
TypeScript 2.7.2

**Current behavior:**
Using a compose element to include a view-model containing a footer element results in the following error:

```
ERROR [templating-resources] RangeError: Maximum call stack size exceeded
    at Container.invoke (webpack-internal:///./node_modules/aurelia-dependency-injection/dist/native-modules/aurelia-dependency-injection.js:707:13)
    at ProviderResolver.get (webpack-internal:///./node_modules/aurelia-templating/dist/native-modules/aurelia-templating.js:2074:72)
    at Container.get (webpack-internal:///./node_modules/aurelia-dependency-injection/dist/native-modules/aurelia-dependency-injection.js:644:21)
    at Container.elementContainerGet [as get] (webpack-internal:///./node_modules/aurelia-templating/dist/native-modules/aurelia-templating.js:2129:15)
    at HtmlBehaviorResource.create (webpack-internal:///./node_modules/aurelia-templating/dist/native-modules/aurelia-templating.js:4116:56)
    at applyInstructions (webpack-internal:///./node_modules/aurelia-templating/dist/native-modules/aurelia-templating.js:2231:31)
    at ViewFactory.create (webpack-internal:///./node_modules/aurelia-templating/dist/native-modules/aurelia-templating.js:2452:7)
    at HtmlBehaviorResource.create (webpack-internal:///./node_modules/aurelia-templating/dist/native-modules/aurelia-templating.js:4128:39)
    at applyInstructions (webpack-internal:///./node_modules/aurelia-templating/dist/native-modules/aurelia-templating.js:2231:31)
    at ViewFactory.create (webpack-internal:///./node_modules/aurelia-templating/dist/native-modules/aurelia-templating.js:2452:7)
    at HtmlBehaviorResource.create (webpack-internal:///./node_modules/aurelia-templating/dist/native-modules/aurelia-templating.js:4128:39)
    at applyInstructions (webpack-internal:///./node_modules/aurelia-templating/dist/native-modules/aurelia-templating.js:2231:31)
    at ViewFactory.create (webpack-internal:///./node_modules/aurelia-templating/dist/native-modules/aurelia-templating.js:2452:7)
    at HtmlBehaviorResource.create (webpack-internal:///./node_modules/aurelia-templating/dist/native-modules/aurelia-templating.js:4128:39)
    at applyInstructions (webpack-internal:///./node_modules/aurelia-templating/dist/native-modules/aurelia-templating.js:2231:31)
    at ViewFactory.create (webpack-internal:///./node_modules/aurelia-templating/dist/native-modules/aurelia-templating.js:2452:7)
    at HtmlBehaviorResource.create (webpack-internal:///./node_modules/aurelia-templating/dist/native-modules/aurelia-templating.js:4128:39)
    at applyInstructions (webpack-internal:///./node_modules/aurelia-templating/dist/native-modules/aurelia-templating.js:2231:31)
    at ViewFactory.create (webpack-internal:///./node_modules/aurelia-templating/dist/native-modules/aurelia-templating.js:2452:7)
    at HtmlBehaviorResource.create (webpack-internal:///./node_modules/aurelia-templating/dist/native-modules/aurelia-templating.js:4128:39)
    at applyInstructions (webpack-internal:///./node_modules/aurelia-templating/dist/native-modules/aurelia-templating.js:2231:31)
    at ViewFactory.create (webpack-internal:///./node_modules/aurelia-templating/dist/native-modules/aurelia-templating.js:2452:7)
From previous event:
    at CompositionEngine.createController (webpack-internal:///./node_modules/aurelia-templating/dist/native-modules/aurelia-templating.js:4619:8)
    at CompositionEngine._createControllerAndSwap (webpack-internal:///./node_modules/aurelia-templating/dist/native-modules/aurelia-templating.js:4581:17)
    at CompositionEngine.compose (webpack-internal:///./node_modules/aurelia-templating/dist/native-modules/aurelia-templating.js:4667:19)
    at processChanges (webpack-internal:///aurelia-templating-resources/compose:185:55)
    at Compose.bind (webpack-internal:///aurelia-templating-resources/compose:96:5)
    at Controller.bind (webpack-internal:///./node_modules/aurelia-templating/dist/native-modules/aurelia-templating.js:3501:22)
    at View.bind (webpack-internal:///./node_modules/aurelia-templating/dist/native-modules/aurelia-templating.js:1490:22)
    at Controller.bind (webpack-internal:///./node_modules/aurelia-templating/dist/native-modules/aurelia-templating.js:3493:17)
    at Controller.automate (webpack-internal:///./node_modules/aurelia-templating/dist/native-modules/aurelia-templating.js:3438:10)
    at eval (webpack-internal:///./node_modules/aurelia-templating/dist/native-modules/aurelia-templating.js:4582:18)
From previous event:
    at CompositionEngine._createControllerAndSwap (webpack-internal:///./node_modules/aurelia-templating/dist/native-modules/aurelia-templating.js:4581:43)
    at CompositionEngine.compose (webpack-internal:///./node_modules/aurelia-templating/dist/native-modules/aurelia-templating.js:4667:19)
    at TemplatingEngine.compose (webpack-internal:///./node_modules/aurelia-templating/dist/native-modules/aurelia-templating.js:4931:36)
    at Aurelia.setRoot (webpack-internal:///aurelia-framework:526:19)
    at eval (webpack-internal:///main:27:55)
From previous event:
    at Module.configure (webpack-internal:///main:27:21)
    at eval (webpack-internal:///./node_modules/aurelia-bootstrapper/dist/native-modules/aurelia-bootstrapper.js:101:27)
From previous event:
    at config (webpack-internal:///./node_modules/aurelia-bootstrapper/dist/native-modules/aurelia-bootstrapper.js:96:54)
    at eval (webpack-internal:///./node_modules/aurelia-bootstrapper/dist/native-modules/aurelia-bootstrapper.js:132:12)
From previous event:
    at bootstrap (webpack-internal:///./node_modules/aurelia-bootstrapper/dist/native-modules/aurelia-bootstrapper.js:131:24)
    at eval (webpack-internal:///./node_modules/aurelia-bootstrapper/dist/native-modules/aurelia-bootstrapper.js:118:7)
From previous event:
    at run (webpack-internal:///./node_modules/aurelia-bootstrapper/dist/native-modules/aurelia-bootstrapper.js:113:59)
    at Module.eval (webpack-internal:///./node_modules/aurelia-bootstrapper/dist/native-modules/aurelia-bootstrapper.js:138:16)
    at eval (webpack-internal:///./node_modules/aurelia-bootstrapper/dist/native-modules/aurelia-bootstrapper.js:139:30)
    at Module../node_modules/aurelia-bootstrapper/dist/native-modules/aurelia-bootstrapper.js (http://localhost:9000/app.77f09c3beb8536a8a5a9.bundle.js:109:1)
    at __webpack_require__ (http://localhost:9000/app.77f09c3beb8536a8a5a9.bundle.js:20:30)
    at Object.0 (http://localhost:9000/app.77f09c3beb8536a8a5a9.bundle.js:620:18)
    at __webpack_require__ (http://localhost:9000/app.77f09c3beb8536a8a5a9.bundle.js:20:30)
    at http://localhost:9000/app.77f09c3beb8536a8a5a9.bundle.js:84:18
    at http://localhost:9000/app.77f09c3beb8536a8a5a9.bundle.js:87:10
```

**Expected/desired behavior:**
I created a Gist for this issue, but it would not allow me to save. Instead, I created a repository that displays the issue: [https://github.com/YardGnomeNinja/AureliaTemplatingFooterTest](https://github.com/YardGnomeNinja/AureliaTemplatingFooterTest)

* **What is the expected behavior?**
A compose element containing a footer element should not result in error.

**Comment by StrahilKazlachev** [comment]
Are you sure the *footer* view and VM are in the build? You are passing a *moduleId* to `<compose>` but I don't see anywhere something like `PLATFORM.moduleName('resources/elements/footer');`.

**Comment by YardGnomeNinja** [comment]
In my main project, where I discovered this issue, I have a number of compose elements defined in this way without issue. I have not defined any of them as modules.

I have also tested by commenting out only the `footer` element and retained the rest of the content of footer.html and found it to work as long as `footer` was commented out.

**Comment by YardGnomeNinja** [comment]
I've also just discovered, this happens with an `aside` element as well. Again, as long as I comment out the `aside` element and retain the contents of the element, the page loads without error.

**Comment by YardGnomeNinja** [comment]
For sake of thoroughness, I added `.plugin(PLATFORM.moduleName('resources/elements/footer')` to `aurelia.use` in main.ts and the issue remains.

**Comment by StrahilKazlachev** [comment]
I did not mean to pass it to `Aurelia.plugin` - it is not a plugin.

**Comment by YardGnomeNinja** [comment]
Sorry, I'm new to the whole Webpack thing. I've only ever seen anything included that way as a plugin. What is the alternative?

**Comment by StrahilKazlachev** [comment]
So the issue turns out different, as by @bigopon 's explanation, the issue is the VM name `class Footer`. By convention this turns in a custom element - `<footer>`. Also custom elements are available in themselves. So now in the view(`footer.html`) you have a recursion.

**Comment by YardGnomeNinja** [comment]
That makes perfect sense. Sorry for posting an issue about it. I wasn't aware that was how that worked. Thanks for your insight!
