### ISSUE TITLE
Global Functions not available to be called in template

### ISSUE THREAD

**Issue by AshleyGrant** [aurelia/templating-resources#6]
The following will fail.

```html
<h2>${encodeURI(heading)}</h2>
```

Is this by design or a bug?

Stack trace is:
```
Potentially unhandled rejection [1] Error: encodeURI is not a function
    at ensureFunctionFromMap (http://localhost:9000/jspm_packages/github/aurelia/binding@0.3.2/system/ast.js:58:13)
    at CallScope.evaluate (http://localhost:9000/jspm_packages/github/aurelia/binding@0.3.2/system/ast.js:652:22)
    at CallScope.connect (http://localhost:9000/jspm_packages/github/aurelia/binding@0.3.2/system/ast.js:692:29)
    at InterpolationBinding.connect (http://localhost:9000/jspm_packages/github/aurelia/templating-binding@0.8.3/system/binding-language.js:232:35)
    at InterpolationBinding.bind (http://localhost:9000/jspm_packages/github/aurelia/templating-binding@0.8.3/system/binding-language.js:201:22)
    at View.bind (http://localhost:9000/jspm_packages/github/aurelia/templating@0.8.6/system/view.js:69:29)
    at RouterView.swap (http://localhost:9000/jspm_packages/github/aurelia/templating-router@0.9.2/system/router-view.js:85:49)
    at http://localhost:9000/jspm_packages/github/aurelia/router@0.5.1/system/navigation-context.js:72:37
    at Array.forEach (native)
    at http://localhost:9000/jspm_packages/github/aurelia/router@0.5.1/system/navigation-context.js:71:28es6-module-loader.src.js:139 (anonymous function)es6-module-loader.src.js:166 fes6-module-loader.src.js:188 i
```

**Comment by AshleyGrant** [comment]
Wrong repo.
