### ISSUE TITLE
Repeat.for collection expression issue (array of objects)

### ISSUE THREAD

**Issue by wshayes** [aurelia/templating-resources#75]
Repeat.for issue in a Plunker: http://plnkr.co/edit/rOL3Wj?p=preview

Workaround suggest by Aaike uses a function to return the array of objects instead of 
    <div class="row" repeat.for="item of $parent.results.facets[facet.name]">

Line 36 in app.html is the issue. If one comments out that div, you can see the page. The javascript console shows the issue with the repeat.for collection. If no one here sees anything wrong, I'll submit it as an issue to the aurelia/templating github repo (or should it be the aurelia/templating-resources?).

    Unhandled promise rejection TypeError: Cannot set property 'targetProperty' of undefined
    at configureProperties (http://localhost:9001/jspm_packages/github/aurelia/templating@0.12.1/view-compiler.js:34:32)
    at ViewCompiler.compileElement (http://localhost:9001/jspm_packages/github/aurelia/templating@0.12.1/view-compiler.js:241:19)
    at ViewCompiler.compileNode (http://localhost:9001/jspm_packages/github/aurelia/templating@0.12.1/view-compiler.js:126:27)
    at ViewCompiler.compileElement (http://localhost:9001/jspm_packages/github/aurelia/templating@0.12.1/view-compiler.js:314:35)
    at ViewCompiler.compileNode (http://localhost:9001/jspm_packages/github/aurelia/templating@0.12.1/view-compiler.js:126:27)
    at ViewCompiler.compileNode (http://localhost:9001/jspm_packages/github/aurelia/templating@0.12.1/view-compiler.js:140:37)
    at ViewCompiler.compile (http://localhost:9001/jspm_packages/github/aurelia/templating@0.12.1/view-compiler.js:109:16)
    at HtmlBehaviorResource.compile (http://localhost:9001/jspm_packages/github/aurelia/templating@0.12.1/html-behavior.js:185:50)
    at ViewCompiler.compileElement (http://localhost:9001/jspm_packages/github/aurelia/templating@0.12.1/view-compiler.js:276:44)
    at ViewCompiler.compileNode (http://localhost:9001/jspm_packages/github/aurelia/templating@0.12.1/view-compiler.js:126:27)(anonymous function) @ es6.promise.js:139module.exports @ $.invoke.js:6queue.(anonymous function) @ $.task.js:40run @ $.task.js:27listner @ $.task.js:31postMessage (async)defer @ $.task.js:54setTask @ $.task.js:42(anonymous function) @ es6.promise.js:134setTimeout (async)$reject @ es6.promise.js:133(anonymous function) @ $.ctx.js:10run @ es6.promise.js:91(anonymous function) @ es6.promise.js:105module.exports @ $.invoke.js:6queue.(anonymous function) @ $.task.js:40run @ $.task.js:27listner @ $.task.js:31postMessage (async)defer @ $.task.js:54setTask @ $.task.js:42notify @ es6.promise.js:79$reject @ es6.promise.js:145(anonymous function) @ $.ctx.js:10run @ es6.promise.js:99(anonymous function) @ es6.promise.js:105module.exports @ $.invoke.js:6queue.(anonymous function) @ $.task.js:40run @ $.task.js:27listner @ $.task.js:31postMessage (async)defer @ $.task.js:54setTask @ $.task.js:42notify @ es6.promise.js:79$reject @ es6.promise.js:145(anonymous function) @ $.ctx.js:10run @ es6.promise.js:91(anonymous function) @ es6.promise.js:105module.exports @ $.invoke.js:6queue.(anonymous function) @ $.task.js:40run @ $.task.js:27listner @ $.task.js:31

**Comment by Aaike** [comment]
for easy reference this issue involves the repeat failing to get an array from an object by specifying the key with a variable, ie:
```
<div repeat.for="item of object[facet.name]">
```
where `object` is an object that holds arrays mapped by keys.

**Comment by boazblake** [comment]
I think this issue has come back?

I am using the latest skeleton esnext-webpack

![screenshot from 2017-09-12 07-40-42](https://user-images.githubusercontent.com/3834931/30326307-c9c91ca6-978d-11e7-9318-a60bf1dc78e3.png)
![screenshot from 2017-09-12 07-39-15](https://user-images.githubusercontent.com/3834931/30326306-c9c6026e-978d-11e7-8212-838f3aeb4b48.png)

**Comment by boazblake** [comment]
I think this should be re-opened
https://stackoverflow.com/questions/46186870/aurelia-repeat-for-throws-an-undefined-error-with-custom-element
